name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -s -X POST https://api.netlify.com/build_hooks/6a5736b0a251fd0f486def34
